server:
  port: ${PORT:9001}
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: g0
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging:
  level:
    root: info
    pl:
      sparkidea: debug
    org:
      apache:
        kafka: debug
      springframework:
        kafka: debug
